name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    name: Build and release gdvm
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            TARGET: linux
            CMD_BUILD: |
              ./ubuntu-dependencies
              make build
              cd dist
              tar -czvf linux.tar.gz pdfcover
            OUT_FILE_NAME: dist/linux.tar.gz
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: |
              ./macos-dependencies
              make build
              cd dist
              tar -czvf macos.tar.gz pdfcover
            OUT_FILE_NAME: dist/macos.tar.gz
          # - os: windows-latest
          #   TARGET: windows
          #   CMD_BUILD: |
          #     make build &&
          #     mv dist/pdfcover dist/pdfcover.exe
          #   OUT_FILE_NAME: dist/pdfcover.exe
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build with pyinstaller for ${{ matrix.TARGET }}
        run: ${{matrix.CMD_BUILD}}
      - name: Create release for ${{ matrix.TARGET }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{matrix.OUT_FILE_NAME}}
